kind: Deployment
apiVersion: apps/v1
metadata:
  name: malware-feature
spec:
  replicas: 1
  selector:
    matchLabels:
      component: malware-feature
  template:
    metadata:
      labels:
        component: malware-feature
    spec:
      serviceAccountName: spark-driver
      hostname: malware-feature-host
      subdomain: malware-feature-headless
      containers:
        - name: malware-feature
          image: hishailesh77/feature1:v1
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [
           "/opt/spark/bin/spark-submit --name malware-test \
           --master k8s://https://kubernetes.default:443 \
           --deploy-mode client  \
           --class FeatureEngineering1  \
           --conf spark.kubernetes.authenticate.subdmission.caCertFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt  \
           --conf spark.kubernetes.authenticate.submission.oauthTokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token   \
           --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark-driver  \
           --conf spark.kubernetes.namespace=default  \
           --conf spark.executor.instances=12  \
           --conf spark.driver.memory=16g  \
           --conf spark.executor.memory=8g  \
           --conf spark.driver.cores=8  \
           --conf spark.executor.cores=4  \
           --conf spark.memory.offHeap.enabled=true  \
           --conf spark.memory.offHeap.size=8g  \
           --conf spark.hadoop.fs.s3a.access.key=AKIAX3D75DYHLQPYD4IT  \
           --conf spark.hadoop.fs.s3a.secret.key=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  \
           --conf spark.kubernetes.container.image=hishailesh77/feature1:v1  \
           --conf spark.kubernetes.container.image.pullPolicy=Always \
           --conf spark.driver.host=malware-feature-host.malware-feature-headless.default.svc.cluster.local \
           --conf spark.driver.port=20020 \
           local:///opt/spark/work-dir/malwarefeatureengineering_2.11-1.0.jar"
          ]
          ports:
            - containerPort: 4040
            - containerPort: 20020
          resources:
            requests:
              cpu: 100m
---

kind: Service
apiVersion: v1
metadata:
  name: malware-feature-headless
spec:
  clusterIP: None
  selector:
    component: malware-feature
---

kind: Service
apiVersion: v1
metadata:
  name: malware-feature
spec:
  ports:
    - name: history-server
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      port: 20020
      targetPort: 20020

  selector:
    component: malware-feature

---
apiVersion: v1
kind: Service
metadata:
  name: malware-feature-lb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "98.33.119.10/32"
  selector:
    component: malware-feature
  ports:
    - name: history-server
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      protocol: TCP
      port: 20020
      targetPort: 20020
---


