kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      serviceAccountName: spark-driver
      hostname: test-prometheus-host
      subdomain: test-prometheus-headless
      containers:
        - name: test-prometheus
          image: hishailesh77/feature:v1
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-c", "tail -f /dev/null"]
          ports:
            - containerPort: 9091
            - containerPort: 4040
          resources:
            requests:
              cpu: 100m
---
kind: Service
apiVersion: v1
metadata:
  name: spark-svc-headless
spec:
  clusterIP: None
  selector:
    app: spark
---

kind: Service
apiVersion: v1
metadata:
  name: spark-svc
spec:
  ports:
    - name: spark-ui
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      port: 20020
      targetPort: 20020
    - name: metrics
      port: 9091
      targetPort: 9091
  selector:
    app: spark

---
apiVersion: v1
kind: Service
metadata:
  name: spark-lb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "98.33.119.10/32"
  selector:
    app: spark
  ports:
    - name: history-server
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      protocol: TCP
      port: 20020
      targetPort: 20020
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      app: spark
  enableAdminAPI: false

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-spark
  labels:
    app: spark
spec:
  selector:
    matchLabels:
      app: spark
  endpoints:
    - port: metrics
---


