kind: Deployment
apiVersion: apps/v1
metadata:
  name: jupyter-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jupyter-lab
  template:
    metadata:
      labels:
        component: jupyter-lab
    spec:
      serviceAccountName: spark-driver
      hostname: jupyter-lab-host
      subdomain: jupyter-headless
      containers:
        - name: jupyter-lab
          imagePullPolicy: Always
          image: hishailesh77/spark-tf:latest
          command: ["/bin/bash"]
          args: ["-c", "jupyter notebook --no-browser --ip=0.0.0.0 --port 8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''"]
          ports:
            - containerPort: 8888
            - containerPort: 4040
            - containerPort: 20020
            - containerPort: 54321
          resources:
            requests:
              cpu: 100m
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-headless
spec:
  clusterIP: None
  selector:
    component: jupyter-lab

---

kind: Service
apiVersion: v1
metadata:
  name: jupyter-lab
spec:
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
    - name: spark-ui
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      port: 20020
      targetPort: 20020
    - name: h20-port
      port: 54321
      targetPort: 54321
  selector:
    component: jupyter-lab

---

apiVersion: v1
kind: Service
metadata:
  name: jupyter-lb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "98.33.119.10/32"
  selector:
    component: jupyter-lab
  ports:
    - name: juypeter
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: spark-ui
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      protocol: TCP
      port: 20020
      targetPort: 20020
    - name: h20-port
      protocol: TCP
      port: 54321
      targetPort: 54321
---