apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: spark-job
    spec:
      restartPolicy: Never
      serviceAccountName: spark-driver
      hostname: spark-driver-host
      subdomain: spark-svc-headless
      containers:
        - name: spark-job
          image: hishailesh77/malware_spark_job:v1
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [
              "/opt/spark/bin/spark-submit --name spark-job \
           --master k8s://https://kubernetes.default:443 \
           --deploy-mode client  \
           --class FeatureEngineering2  \
           --conf spark.kubernetes.authenticate.subdmission.caCertFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt  \
           --conf spark.kubernetes.authenticate.submission.oauthTokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token   \
           --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark-driver  \
           --conf spark.kubernetes.namespace=default  \
           --conf spark.executor.instances=12  \
           --conf spark.driver.memory=16g  \
           --conf spark.executor.memory=8g  \
           --conf spark.driver.cores=8  \
           --conf spark.executor.cores=4  \
           --conf spark.memory.offHeap.enabled=true  \
           --conf spark.memory.offHeap.size=8g  \
           --conf spark.hadoop.fs.s3a.access.key=AKIAX3D75DYHLQPYD4IT  \
           --conf spark.hadoop.fs.s3a.secret.key=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  \
           --conf spark.kubernetes.container.image=hishailesh77/malware_spark_job:v1 \
           --conf spark.kubernetes.container.image.pullPolicy=Always \
           --conf spark.driver.host=spark-driver-host.spark-svc-headless.default.svc.cluster.local \
           --conf spark.driver.port=20020 \
           local:///opt/spark/work-dir/malwarefeatureengineering_2.12-2.0.jar"
          ]
          ports:
            - containerPort: 4040
            - containerPort: 20020
          resources:
            requests:
              cpu: 100m
---

kind: Service
apiVersion: v1
metadata:
  name: spark-svc-headless
spec:
  clusterIP: None
  selector:
    app: spark-job
---

kind: Service
apiVersion: v1
metadata:
  name: spark-svc
spec:
  ports:
    - name: history-server
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      port: 20020
      targetPort: 20020
  selector:
    app: spark-job

---
apiVersion: v1
kind: Service
metadata:
  name: spark-lb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "98.33.119.10/32"
  selector:
    app: spark-job
  ports:
    - name: history-server
      protocol: TCP
      port: 4040
      targetPort: 4040
    - name: spark-driver-port
      protocol: TCP
      port: 20020
      targetPort: 20020
---


